# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dCNegBin <- function(dY, dN, dP, dLambda, bLog = TRUE, iTrunc = 50L) {
    .Call(`_hmminar_dCNegBin`, dY, dN, dP, dLambda, bLog, iTrunc)
}

dLLK_cNegBin <- function(vY, dN, dP, dLambda) {
    .Call(`_hmminar_dLLK_cNegBin`, vY, dN, dP, dLambda)
}

EM_CNegBin <- function(vY, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_CNegBin`, vY, dTol, iMaxiter)
}

EM_MSSumMixPois <- function(vY, iJ, iL, vMu, vNu, vOmega, mGamma, dTol = 1e-7, iMaxiter = 4000L) {
    .Call(`_hmminar_EM_MSSumMixPois`, vY, iJ, iL, vMu, vNu, vOmega, mGamma, dTol, iMaxiter)
}

EM_MSSumMixPois_Dummy <- function(vY, iJ, iL, vMu, vNu, vOmega, mGamma, vBeta, mD, dTol = 1e-7, iMaxiter = 4000L) {
    .Call(`_hmminar_EM_MSSumMixPois_Dummy`, vY, iJ, iL, vMu, vNu, vOmega, mGamma, vBeta, mD, dTol, iMaxiter)
}

EMInar <- function(vY, vLogFactorial_K, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EMInar`, vY, vLogFactorial_K, dTol, iMaxiter)
}

EMMixInar <- function(vY, iJ, vOmega, dAlpha, vLambda, vLogFactorial_K, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EMMixInar`, vY, iJ, vOmega, dAlpha, vLambda, vLogFactorial_K, dTol, iMaxiter)
}

EMMixInar_Seasonal <- function(vY, iJ, vOmega, dAlpha, vLambda, vBeta, vLogFactorial_K, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EMMixInar_Seasonal`, vY, iJ, vOmega, dAlpha, vLambda, vBeta, vLogFactorial_K, mD, dTol, iMaxiter)
}

EMMixInar_Seasonal2 <- function(vY, iJ, vOmega, dAlpha, vLambda, vBeta, vLogFactorial_K, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EMMixInar_Seasonal2`, vY, iJ, vOmega, dAlpha, vLambda, vBeta, vLogFactorial_K, mD, dTol, iMaxiter)
}

EMMixInarP_Seasonal <- function(vY, iJ, iP, vOmega, dAlpha, vLambda, vBeta, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EMMixInarP_Seasonal`, vY, iJ, iP, vOmega, dAlpha, vLambda, vBeta, mD, dTol, iMaxiter)
}

dPOI <- function(dY, dLambda, iLog) {
    .Call(`_hmminar_dPOI`, dY, dLambda, iLog)
}

EM_Mixture_Pois <- function(vY, iJ, maxIter = 1e3L, tol = 1e-8) {
    .Call(`_hmminar_EM_Mixture_Pois`, vY, iJ, maxIter, tol)
}

EM_NegBin <- function(vY, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_NegBin`, vY, dTol, iMaxiter)
}

EM_Neyman <- function(vY, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_Neyman`, vY, dTol, iMaxiter)
}

EM_SumMixPois <- function(vY, iJ, dMu, vNu, vOmega, dTol = 1e-6, iMaxiter = 4000L) {
    .Call(`_hmminar_EM_SumMixPois`, vY, iJ, dMu, vNu, vOmega, dTol, iMaxiter)
}

FFBS <- function(allprobs, delta, mGamma, iJ, iT) {
    .Call(`_hmminar_FFBS`, allprobs, delta, mGamma, iJ, iT)
}

FFBS_robust <- function(lallprobs, delta, mGamma, iJ, iT) {
    .Call(`_hmminar_FFBS_robust`, lallprobs, delta, mGamma, iJ, iT)
}

EM_MSMixInar <- function(vY, iJ, iM, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD, vLogFactorial_K, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_MSMixInar`, vY, iJ, iM, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD, vLogFactorial_K, dTol, iMaxiter)
}

EM_MSMixInar_OmegaChain <- function(vY, iJ, iM, mOmega, vLambda, dAlpha, mGamma, vDelta, vBeta, mD, vLogFactorial_K, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_MSMixInar_OmegaChain`, vY, iJ, iM, mOmega, vLambda, dAlpha, mGamma, vDelta, vBeta, mD, vLogFactorial_K, dTol, iMaxiter)
}

EM_MSMixInar_v2 <- function(vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_MSMixInar_v2`, vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD, dTol, iMaxiter)
}

Filtering_MSMixInar_v2_Seasonal_Dummy_Inv <- function(vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Filtering_MSMixInar_v2_Seasonal_Dummy_Inv`, vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD)
}

EM_MSMixInar_v3 <- function(vY, iJ, iM, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_MSMixInar_v3`, vY, iJ, iM, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD, dTol, iMaxiter)
}

Filtering_MSMixInar_Seasonal_Dummy <- function(vY, iJ, iM, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Filtering_MSMixInar_Seasonal_Dummy`, vY, iJ, iM, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD)
}

Filtering_MSMixInar_v3_Seasonal_Dummy <- function(vY, iJ, iM, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Filtering_MSMixInar_v3_Seasonal_Dummy`, vY, iJ, iM, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD)
}

Sim_MSMixInar_Seasonal_Dummy <- function(iT, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Sim_MSMixInar_Seasonal_Dummy`, iT, vOmega, vLambda, vAlpha, mGamma, vDelta, vBeta, mD)
}

Sim_MSMixInar_v2_Seasonal_Dummy <- function(iT, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Sim_MSMixInar_v2_Seasonal_Dummy`, iT, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD)
}

Sim_MSMixInar_v3_Seasonal_Dummy <- function(iT, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Sim_MSMixInar_v3_Seasonal_Dummy`, iT, vOmega, mLambda, dAlpha, mGamma, vDelta, vBeta, mD)
}

Filtering_MSMixInar_v2_Seasonal_Dummy <- function(vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Filtering_MSMixInar_v2_Seasonal_Dummy`, vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD)
}

EM_MSMixInar_v2_Inv <- function(vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD, dTol = 1e-4, iMaxiter = 1000L) {
    .Call(`_hmminar_EM_MSMixInar_v2_Inv`, vY, iJ, iM, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD, dTol, iMaxiter)
}

Sim_MSMixInar_v2_Seasonal_Dummy_Inv <- function(iT, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD) {
    .Call(`_hmminar_Sim_MSMixInar_v2_Seasonal_Dummy_Inv`, iT, vOmega, vLambda, vMu, dAlpha, mGamma, vDelta, vBeta, mD)
}

EM_MSMixInarTwoChains_Dummy_C2 <- function(vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, vSeason, vLogFactorial_K, maxIter = 1e3L, tol = 1e-4, bSeasonal = TRUE) {
    .Call(`_hmminar_EM_MSMixInarTwoChains_Dummy_C2`, vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, vSeason, vLogFactorial_K, maxIter, tol, bSeasonal)
}

EM_MSMixInarTwoChains_Dummy_C_AlphaCor <- function(vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, dVarPhi, vSeason, vLogFactorial_K, vO, maxIter = 1e3L, tol = 1e-4, bSeasonal = TRUE, bFilter = FALSE) {
    .Call(`_hmminar_EM_MSMixInarTwoChains_Dummy_C_AlphaCor`, vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, dVarPhi, vSeason, vLogFactorial_K, vO, maxIter, tol, bSeasonal, bFilter)
}

EM_MSMixInarTwoChains_Dummy_C_AlphaCor_OmegaIdentity <- function(vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, dVarPhi, vSeason, vLogFactorial_K, vO, maxIter = 1e3L, tol = 1e-4, bSeasonal = TRUE, bFilter = FALSE) {
    .Call(`_hmminar_EM_MSMixInarTwoChains_Dummy_C_AlphaCor_OmegaIdentity`, vY, iJ, iK, iL, mGamma_Eta, mGamma_Alpha, mOmega, vLambda, vAlpha, vBeta, dVarPhi, vSeason, vLogFactorial_K, vO, maxIter, tol, bSeasonal, bFilter)
}

InitializeBeta_INAR <- function(vY, vBeta, vSeason, vLogFactorial_K, iMaxiter = 1e3L, dTol = 1e-4) {
    .Call(`_hmminar_InitializeBeta_INAR`, vY, vBeta, vSeason, vLogFactorial_K, iMaxiter, dTol)
}

Sim_MSMixInarTwoChains <- function(iT, mOmega, vLambda, vAlpha, mGamma_Alpha, mGamma_Eta, vBeta, mD) {
    .Call(`_hmminar_Sim_MSMixInarTwoChains`, iT, mOmega, vLambda, vAlpha, mGamma_Alpha, mGamma_Eta, vBeta, mD)
}

Sim_MSMixInarTwoChains_AlphaCor <- function(iT, mOmega, vLambda, vAlpha, mGamma_Alpha, mGamma_Eta, vBeta, dVarPhi, vO, vSeason) {
    .Call(`_hmminar_Sim_MSMixInarTwoChains_AlphaCor`, iT, mOmega, vLambda, vAlpha, mGamma_Alpha, mGamma_Eta, vBeta, dVarPhi, vO, vSeason)
}

Sim_MSMixInarOneChain_AlphaCor <- function(iT, vLambda, vAlpha, mGamma, vBeta, dVarPhi, vO, vSeason) {
    .Call(`_hmminar_Sim_MSMixInarOneChain_AlphaCor`, iT, vLambda, vAlpha, mGamma, vBeta, dVarPhi, vO, vSeason)
}

Sim_INAR <- function(iT, dAlpha, dLambda) {
    .Call(`_hmminar_Sim_INAR`, iT, dAlpha, dLambda)
}

dE1 <- function(mGamma_OmegaZB, mIndices, vLambda, vAlpha) {
    .Call(`_hmminar_dE1`, mGamma_OmegaZB, mIndices, vLambda, vAlpha)
}

dE2 <- function(mGamma_OmegaZB, mIndices, vLambda, vAlpha) {
    .Call(`_hmminar_dE2`, mGamma_OmegaZB, mIndices, vLambda, vAlpha)
}

dFoo <- function(mGamma_OmegaZB, mIndices, vLambda, vAlpha) {
    .Call(`_hmminar_dFoo`, mGamma_OmegaZB, mIndices, vLambda, vAlpha)
}

UnMapC <- function(x, L, U) {
    .Call(`_hmminar_UnMapC`, x, L, U)
}

mapC_v <- function(x, L, U) {
    .Call(`_hmminar_mapC_v`, x, L, U)
}

UnmapC_v <- function(x, L, U) {
    .Call(`_hmminar_UnmapC_v`, x, L, U)
}

SimplexMapping <- function(vOmega_tilde, M) {
    .Call(`_hmminar_SimplexMapping`, vOmega_tilde, M)
}

SimplexUnMapping <- function(vOmega, M) {
    .Call(`_hmminar_SimplexUnMapping`, vOmega, M)
}

Sim_MixInar <- function(iT, vOmega, vLambda, dAlpha) {
    .Call(`_hmminar_Sim_MixInar`, iT, vOmega, vLambda, dAlpha)
}

Sim_MixInar_Seasonal <- function(iT, iS, vOmega, vLambda, dAlpha, vEta) {
    .Call(`_hmminar_Sim_MixInar_Seasonal`, iT, iS, vOmega, vLambda, dAlpha, vEta)
}

Sim_MixInar_Seasonal_Dummy <- function(iT, vOmega, vLambda, dAlpha, vBeta, mD) {
    .Call(`_hmminar_Sim_MixInar_Seasonal_Dummy`, iT, vOmega, vLambda, dAlpha, vBeta, mD)
}

Filtering_MixInar_C <- function(vY, iJ, vOmega, dAlpha, vLambda, vBeta, mD) {
    .Call(`_hmminar_Filtering_MixInar_C`, vY, iJ, vOmega, dAlpha, vLambda, vBeta, mD)
}

FilteringMedian_MixInar_C <- function(vY, iJ, vOmega, dAlpha, vLambda, vBeta, mD, iB = 5000L) {
    .Call(`_hmminar_FilteringMedian_MixInar_C`, vY, iJ, vOmega, dAlpha, vLambda, vBeta, mD, iB)
}

Moments_C <- function(PredictedProb, iJ, iL, vMu, vNu, vOmega, mGamma, vBeta, mD) {
    .Call(`_hmminar_Moments_C`, PredictedProb, iJ, iL, vMu, vNu, vOmega, mGamma, vBeta, mD)
}

dNB <- function(dY, dDelta, dBeta, bLog = TRUE) {
    .Call(`_hmminar_dNB`, dY, dDelta, dBeta, bLog)
}

pNB <- function(dY, dDelta, dBeta, bLog = TRUE) {
    .Call(`_hmminar_pNB`, dY, dDelta, dBeta, bLog)
}

NBAR <- function(vY, dBeta, dDelta0, dOmega0) {
    .Call(`_hmminar_NBAR`, vY, dBeta, dDelta0, dOmega0)
}

PNBAR <- function(vY, dBeta, dDelta0, dOmega0, dOmega1, dOmega2, iS) {
    .Call(`_hmminar_PNBAR`, vY, dBeta, dDelta0, dOmega0, dOmega1, dOmega2, iS)
}

dNBin <- function(dY, dN, dP, bLog = TRUE) {
    .Call(`_hmminar_dNBin`, dY, dN, dP, bLog)
}

pNBin <- function(dY, dN, dP, bLog = TRUE) {
    .Call(`_hmminar_pNBin`, dY, dN, dP, bLog)
}

NBSoftplusSeasonalINGARCH_filter <- function(vY, dM0, dAlpha0, dAlpha1, dBeta1, vDelta_S, iS, dC, dP) {
    .Call(`_hmminar_NBSoftplusSeasonalINGARCH_filter`, vY, dM0, dAlpha0, dAlpha1, dBeta1, vDelta_S, iS, dC, dP)
}

NBSoftplusSeasonalINGARCH_DummySeason_filter <- function(vY, dM0, dAlpha0, dAlpha1, dBeta1, vSeason, vBeta_s, dC, dP) {
    .Call(`_hmminar_NBSoftplusSeasonalINGARCH_DummySeason_filter`, vY, dM0, dAlpha0, dAlpha1, dBeta1, vSeason, vBeta_s, dC, dP)
}

dNegBin <- function(dY, dN, dP, bLog = TRUE) {
    .Call(`_hmminar_dNegBin`, dY, dN, dP, bLog)
}

rlogarithmic <- function(p) {
    .Call(`_hmminar_rlogarithmic`, p)
}

rNegBin <- function(dN, dP) {
    .Call(`_hmminar_rNegBin`, dN, dP)
}

dNeyman2 <- function(dY, dNu, dMu, bLog = TRUE, iTrunc = 100L) {
    .Call(`_hmminar_dNeyman2`, dY, dNu, dMu, bLog, iTrunc)
}

dNeyman <- function(dY, dNu, dMu, bLog = TRUE, iTrunc = 100L) {
    .Call(`_hmminar_dNeyman`, dY, dNu, dMu, bLog, iTrunc)
}

rNeyman <- function(dNu, dMu) {
    .Call(`_hmminar_rNeyman`, dNu, dMu)
}

dPB2 <- function(dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dPB2`, dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog)
}

dPB <- function(dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dPB`, dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog)
}

dMixPB <- function(dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dMixPB`, dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K, bLog)
}

pPB <- function(dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_pPB`, dY, dX, dAlpha, dLambda, vLogFactorial_K, bLog)
}

pMixPB <- function(dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_pMixPB`, dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K, bLog)
}

dLLK_MixPB <- function(vY, vLambda, vOmega, vLogFactorial_K, dAlpha, iT, iJ) {
    .Call(`_hmminar_dLLK_MixPB`, vY, vLambda, vOmega, vLogFactorial_K, dAlpha, iT, iJ)
}

dLLK_MixPB_seasonal <- function(vY, vLambda, vOmega, vEta, vLogFactorial_K, dAlpha, iT, iJ, iS) {
    .Call(`_hmminar_dLLK_MixPB_seasonal`, vY, vLambda, vOmega, vEta, vLogFactorial_K, dAlpha, iT, iJ, iS)
}

dSumThreeBinom <- function(dY, vK, vPi, bLog = TRUE) {
    .Call(`_hmminar_dSumThreeBinom`, dY, vK, vPi, bLog)
}

dSumThreeBinom_Eff <- function(dY, vK, vPi, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumThreeBinom_Eff`, dY, vK, vPi, vLogFactorial_K, bLog)
}

dSumThreeBinom_Approx <- function(dY, vK, vPi, bLog = TRUE) {
    .Call(`_hmminar_dSumThreeBinom_Approx`, dY, vK, vPi, bLog)
}

dSumMixThreeBinom <- function(dY, dK, vPi, vOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumMixThreeBinom`, dY, dK, vPi, vOmega, vLogFactorial_K, bLog)
}

dSumMixThreeBinom_Approx <- function(dY, dK, vPi, vOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumMixThreeBinom_Approx`, dY, dK, vPi, vOmega, vLogFactorial_K, bLog)
}

dSumMixThreeBinom_foo <- function(dY, dK, vPi, vOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumMixThreeBinom_foo`, dY, dK, vPi, vOmega, vLogFactorial_K, bLog)
}

dPoissonSumMixThreeBinom <- function(dY, dLambda, vPi, vOmega, bLog = TRUE) {
    .Call(`_hmminar_dPoissonSumMixThreeBinom`, dY, dLambda, vPi, vOmega, bLog)
}

dLLKPoissonSumMixThreeBinom <- function(vY, dLambda, vPi, vOmega, vLogFactorial_K, iT, iMax, iCores = 7L) {
    .Call(`_hmminar_dLLKPoissonSumMixThreeBinom`, vY, dLambda, vPi, vOmega, vLogFactorial_K, iT, iMax, iCores)
}

dLLKPoissonSumMixThreeBinom_fast <- function(vY, dLambda, vPi, vOmega, vLogFactorial_K, iT, iMax, iCores = 7L) {
    .Call(`_hmminar_dLLKPoissonSumMixThreeBinom_fast`, vY, dLambda, vPi, vOmega, vLogFactorial_K, iT, iMax, iCores)
}

dLLKSumMixThreeBinom <- function(vY, dK, vPi, vOmega, vLogFactorial_K, iT) {
    .Call(`_hmminar_dLLKSumMixThreeBinom`, vY, dK, vPi, vOmega, vLogFactorial_K, iT)
}

rSumMixThreeBinom <- function(iT, dK, vPi, vOmega) {
    .Call(`_hmminar_rSumMixThreeBinom`, iT, dK, vPi, vOmega)
}

rPoissonSumMixThreeBinom <- function(iT, dLambda, vPi, vOmega) {
    .Call(`_hmminar_rPoissonSumMixThreeBinom`, iT, dLambda, vPi, vOmega)
}

f_i <- function(di, dY, dK, dOmega, vPi, vQ, dConst) {
    .Call(`_hmminar_f_i`, di, dY, dK, dOmega, vPi, vQ, dConst)
}

find_iMax <- function(dY, dK, dOmega, vPi, vQ, dConst, dLower, dUpper, maxiter = 1e4L, eps = 1e-4) {
    .Call(`_hmminar_find_iMax`, dY, dK, dOmega, vPi, vQ, dConst, dLower, dUpper, maxiter, eps)
}

dSumMixTwoBinom <- function(dY, dK, vPi, dOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumMixTwoBinom`, dY, dK, vPi, dOmega, vLogFactorial_K, bLog)
}

dSumMixTwoBinom_Eff <- function(dY, dK, vPi, dOmega, vLogFactorial_K, bLog = TRUE, dTol_Log = -17) {
    .Call(`_hmminar_dSumMixTwoBinom_Eff`, dY, dK, vPi, dOmega, vLogFactorial_K, bLog, dTol_Log)
}

dSumMixTwoBinom_foo <- function(dY, dK, vPi, dOmega, vLogFactorial_K, bLog = TRUE) {
    .Call(`_hmminar_dSumMixTwoBinom_foo`, dY, dK, vPi, dOmega, vLogFactorial_K, bLog)
}

dLLKPoissonSumMixTwoBinom <- function(vY, dLambda, vPi, dOmega, vLogFactorial_K, iT, iMax, iCores = 7L) {
    .Call(`_hmminar_dLLKPoissonSumMixTwoBinom`, vY, dLambda, vPi, dOmega, vLogFactorial_K, iT, iMax, iCores)
}

rSumMixTwoBinom <- function(iT, dK, vPi, dOmega) {
    .Call(`_hmminar_rSumMixTwoBinom`, iT, dK, vPi, dOmega)
}

rNBSumMixTwoBinom <- function(iT, dA, dB, vPi, dOmega) {
    .Call(`_hmminar_rNBSumMixTwoBinom`, iT, dA, dB, vPi, dOmega)
}

rPoissonSumMixTwoBinom_Seasonal <- function(iT, iS, vEta, vPi, dOmega) {
    .Call(`_hmminar_rPoissonSumMixTwoBinom_Seasonal`, iT, iS, vEta, vPi, dOmega)
}

dLLKPoissonSumMixTwoBinom_Seasonal_pre <- function(vY, vPi, dOmega, vEta, vLogFactorial_K, iT, iS, iMax) {
    .Call(`_hmminar_dLLKPoissonSumMixTwoBinom_Seasonal_pre`, vY, vPi, dOmega, vEta, vLogFactorial_K, iT, iS, iMax)
}

dLLKPoissonSumMixTwoBinom_Seasonal <- function(vY, vPi, dOmega, vEta, vLogFactorial_K, iT, iS, iMax) {
    .Call(`_hmminar_dLLKPoissonSumMixTwoBinom_Seasonal`, vY, vPi, dOmega, vEta, vLogFactorial_K, iT, iS, iMax)
}

dLLKNBSumMixTwoBinom <- function(vY, dOmega, vPi, dA, dB, vLogFactorial_K, iT, iMax) {
    .Call(`_hmminar_dLLKNBSumMixTwoBinom`, vY, dOmega, vPi, dA, dB, vLogFactorial_K, iT, iMax)
}

PIT_MixINAR <- function(dU, dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K) {
    .Call(`_hmminar_PIT_MixINAR`, dU, dY, dX, dAlpha, vLambda, vOmega, vLogFactorial_K)
}

AveragePIT_MixINAR <- function(dU, vY, dAlpha, vLambda, vOmega, vBeta, mD, vLogFactorial_K) {
    .Call(`_hmminar_AveragePIT_MixINAR`, dU, vY, dAlpha, vLambda, vOmega, vBeta, mD, vLogFactorial_K)
}

PIT_Bin_MixINAR <- function(iB, vY, dAlpha, vLambda, vOmega, vBeta, mD, vLogFactorial_K) {
    .Call(`_hmminar_PIT_Bin_MixINAR`, iB, vY, dAlpha, vLambda, vOmega, vBeta, mD, vLogFactorial_K)
}

Gamma_enlarged <- function(mGamma_Omega, vOmega) {
    .Call(`_hmminar_Gamma_enlarged`, mGamma_Omega, vOmega)
}

vDelta_enlarged <- function(vDelta, vOmega) {
    .Call(`_hmminar_vDelta_enlarged`, vDelta, vOmega)
}

Indices <- function(iJ, iL) {
    .Call(`_hmminar_Indices`, iJ, iL)
}

Gamma_Enlarged_2 <- function(mGamma_Eta, mOmega, mGamma_Alpha, mIndices) {
    .Call(`_hmminar_Gamma_Enlarged_2`, mGamma_Eta, mOmega, mGamma_Alpha, mIndices)
}

Gamma_Enlarged_2_OmegaChain <- function(mGamma_Eta, mOmega, mIndices) {
    .Call(`_hmminar_Gamma_Enlarged_2_OmegaChain`, mGamma_Eta, mOmega, mIndices)
}

GammaCheck <- function(mGamma, iJ) {
    .Call(`_hmminar_GammaCheck`, mGamma, iJ)
}

OmegaCheck <- function(mOmega, iK, iJ) {
    .Call(`_hmminar_OmegaCheck`, mOmega, iK, iJ)
}

MSSumMixPois_Sim <- function(iT, vMu, vNu, vOmega, mGamma) {
    .Call(`_hmminar_MSSumMixPois_Sim`, iT, vMu, vNu, vOmega, mGamma)
}

MSSumMixPois_Sim_Dummy <- function(iT, vMu, vNu, vOmega, mGamma, vBeta, mD) {
    .Call(`_hmminar_MSSumMixPois_Sim_Dummy`, iT, vMu, vNu, vOmega, mGamma, vBeta, mD)
}

StirlingNumber <- function(iN, iM) {
    .Call(`_hmminar_StirlingNumber`, iN, iM)
}

dStirling <- function(dY, dM, dTheta, bLog = TRUE) {
    .Call(`_hmminar_dStirling`, dY, dM, dTheta, bLog)
}

dSumMixPois <- function(dY, vOmega, vNu, dMu, bLog = TRUE, iTrunc = 100L) {
    .Call(`_hmminar_dSumMixPois`, dY, vOmega, vNu, dMu, bLog, iTrunc)
}

dLLK_SumMixPois <- function(vY, vOmega, vNu, dMu) {
    .Call(`_hmminar_dLLK_SumMixPois`, vY, vOmega, vNu, dMu)
}

rSumMixPois <- function(vOmega, vNu, dMu) {
    .Call(`_hmminar_rSumMixPois`, vOmega, vNu, dMu)
}

MixtDensityScale <- function(vOmega_log, vD_log) {
    .Call(`_hmminar_MixtDensityScale`, vOmega_log, vD_log)
}

LogSumExp <- function(vLog) {
    .Call(`_hmminar_LogSumExp`, vLog)
}

getDelta <- function(gamma, m) {
    .Call(`_hmminar_getDelta`, gamma, m)
}

LW <- function(x, tolerance = 1e-10, maxit = 50L) {
    .Call(`_hmminar_LW`, x, tolerance, maxit)
}

OmegaZB_Indices <- function(iJ, iK, iL) {
    .Call(`_hmminar_OmegaZB_Indices`, iJ, iK, iL)
}

BoundProbs <- function(vP, probbound) {
    .Call(`_hmminar_BoundProbs`, vP, probbound)
}

BoundGamma <- function(mGamma, probbound) {
    .Call(`_hmminar_BoundGamma`, mGamma, probbound)
}

dZTNB <- function(dV, dA, dB, bLog = TRUE) {
    .Call(`_hmminar_dZTNB`, dV, dA, dB, bLog)
}

dSumZTNB <- function(dV, dN, dA, dB, bLog = TRUE) {
    .Call(`_hmminar_dSumZTNB`, dV, dN, dA, dB, bLog)
}

dLLK_SumZTNB <- function(vV, vN, dA, dB) {
    .Call(`_hmminar_dLLK_SumZTNB`, vV, vN, dA, dB)
}

